UCL-CCS/EasyVVUQ

.gitignore, easyvvuq/__init__.py, easyvvuq/campaign.py, easyvvuq/distributions/__init__.py, easyvvuq/distributions/distributions.py, easyvvuq/encoders/generic_template.py, test/templates/cannonsim.template, test/test_cannon_simple_csv.py, test/test_input/test_cannonsim.json, test/test_input/test_cannonsim_simple_csv.json
=> Integer distribution

easyvvuq/campaign.py, easyvvuq/elements/analysis/sc_analysis.py, easyvvuq/elements/sampling/stochastic_collocation.py, fix_pep8.sh, setup.cfg, tests/SC_easyvvuq/ade_output.json, tests/SC_easyvvuq/run_SC_campaign.py
Remove the monkey patch of SC/PCE points and weights to the Campaign object
=> [WIP] Issue 56

easyvvuq/distributions/__init__.py, easyvvuq/distributions/distributions.py, easyvvuq/elements/sampling/random.py, setup.py, tests/test_cannonsim_compare.py, tests/test_cannonsim_csv.py, tests/test_gauss.py, tests/test_gauss_custom_encoder.py, tests/test_gauss_fix.py, tests/test_pce.py
Issue #61 - update tests to use Chaospy distributions instead of the old EasyVVUQ python generator versions
=> Issue 61 dist to chaospy

easyvvuq/campaign.py, easyvvuq/distributions/__init__.py, easyvvuq/distributions/distributions.py, easyvvuq/elements/analysis/pce_analysis.py, easyvvuq/elements/analysis/sc_analysis.py, easyvvuq/elements/sampling/pce.py, easyvvuq/elements/sampling/random.py, easyvvuq/elements/sampling/stochastic_collocation.py, fix_pep8.sh, setup.cfg, setup.py, tests/SC_easyvvuq/ade_output.json, tests/SC_easyvvuq/run_SC_campaign.py, tests/pce/pce_model.py, tests/test_campaign_dir_prefix.py, tests/test_cannonsim_compare.py, tests/test_cannonsim_csv.py, tests/test_gauss.py, tests/test_gauss_add_default_run.py, tests/test_gauss_custom_encoder.py, tests/test_gauss_fix.py, tests/test_pce.py
Don't merge! For preview purposes.
=> [WIP] Initial, basic implementation of abstracted Campaign data storage (enabling SQL backend)

tests/test_worker.py
The previous version did not work on my system. This also has some improvements like using subprocess instead of os.system making it less hacky.
=> Changes to test_worker.py

easyvvuq/db/sql.py, tests/test_db.py
What it says in the the title.
=> CampaignDB test

tests/test_restart.py
Comprehensive tests for the resume campaign resume functionality.
=> Test the restart functionality

easyvvuq/decoders/simple_csv.py, tests/cannonsim/src/cannonsim.cc, tests/cooling/cooling_model.py
Fix Pandas CSV reader to read columns instead of replacing them
=> Fix Pandas CSV reader to read columns properly

easyvvuq/db/sql.py, tests/test_db.py
=> Version check

docs/index.rst, docs/multiencoder_tutorial.rst, easyvvuq/encoders/__init__.py, easyvvuq/encoders/multiencoder.py, tests/test_multiencoder.py
Add the MultiEncoder element as described in Issue #150.
=> Issue150 multiencoder

docs/multiencoder_tutorial.rst, easyvvuq/encoders/DirectoryBuilder.py, easyvvuq/encoders/__init__.py, easyvvuq/encoders/directory_builder.py, tests/test_multiencoder.py
Add a ```DirectoryBuilder``` encoder to build directory hierarchies for each run. Designed primarily to be used in conjunction with other encoders via a ```MultiEncoder```.
=> Issue 155 directory encoder

easyvvuq/campaign.py
=> Allow to modify Campaign prefix

.travis.yml, setup.py
A custom setup.py command to rebuild cannonsim. To address #172
=> Rebuild cannonsim

easyvvuq/analysis/ensemble_boot.py, tests/test_worker.py
To address #164.
Is this more helpful?
=> More helpful error message if a qoi is misnamed

easyvvuq/encoders/jinja_encoder.py, requirements.txt, tests/jinjaencoder/namoptions.template, tests/test_jinja_encoder.py
Another encoder, using the jinja2 template system.
Jinja2 is already a dependency of EasyVVUQ, indirectly through one of the existing dependencies.
=> add jinja2 template encoder

easyvvuq/sampling/stochastic_collocation.py, tests/test_stochastic_collocation.py
Exception instead of hard crash, added a simple test and replace a print with logging command.
=> Small improvements to stochastic collocation sampler

easyvvuq/sampling/__init__.py, easyvvuq/sampling/quasirandom.py, tests/test_quasirandom.py
Added LHC and Halton samplers.
=> Quasirandom

easyvvuq/analysis/sc_analysis.py, easyvvuq/sampling/stochastic_collocation.py, tests/test_anisotropic_order.py
Made it possible to give different polynomial orders for different uncertain variables to create anisotropic grids:
```python
my_sampler = uq.sampling.SCSampler(vary=vary, polynomial_order=[1,4])
```
Only works for stochastic collocation. Does not work for sparse grids.
=> Check order sc

easyvvuq/campaign.py, tests/sc/sparse_sc_test.py
There is a bug in draw_samples where if num_samples is a float that is not exactly an integer it will enter an infinite loop. Which is why using >= and <= is preferable to ==.
=> Fix the draw_samples bug

docs/tutorial_files/easyvvuq_gp.py, easyvvuq/analysis/__init__.py, easyvvuq/analysis/gp_analyse.py, requirements.txt
Using http://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html
=> Gaussian Processes Regression

tests/gauss/gauss_json.py, tests/test_vector.py
changing tests/gauss/gauss_json.py to also output a json file,
with a vector of values. A new test in test_vector.py
tries to use the vector-valued QoI with the SC sampler.
=> add test for vector QoI

tests/test_aggregate_by_variable.py, tests/test_anisotropic_order.py, tests/test_jinja_encoder.py, tests/test_multiapp.py, tests/test_recollate.py
Use in-memory db in the tests where possible. Should address #213
=> In memory db

tests/test_vector.py
Test case for vector QoI and PCE analysis.
=> add vector-QoI test for PCE analysis (fails)

easyvvuq/db/sql.py, easyvvuq/utils/helpers.py, tests/test_utils.py
=> Attempting to fix the multi-index database storage issue.
